const books = [
    { title: 'Bible: NZ (Evangelium podle Jana)', author: '---', name: 'Bible: NZ (Evangelium podle Jana)', genre: ['Svatá kniha'], druh: ['epika'], time: ['Světová a česká literatura do konce 18. století'] },
    { title: 'Bible: SZ (první nebo druhá kniha Mojžíšova)', author: '---', name: 'Bible: SZ (první nebo druhá kniha Mojžíšova)', genre: ['Svatá kniha'], druh: ['epika'], time: ['Světová a česká literatura do konce 18. století'] },
    { title: 'Dekameron', author: 'Giovanni Boccaccio', name: 'Dekameron', genre: ['Novela'], druh: ['epika'], time: ['Světová a česká literatura do konce 18. století'] },
    { title: 'Důmyslný rytíř Don Quijote de la Mancha', author: 'Miguel de Cervantes y Saavedra', name: 'Důmyslný rytíř Don Quijote de la Mancha', genre: ['Pikareskní román'], druh: ['epika'], time: ['Světová a česká literatura do konce 18. století'] },
    { title: 'Jeptiška', author: 'Denis Diderot', name: 'Jeptiška', genre: ['Filosofický román', 'Román'], druh: ['epika'], time: ['Světová a česká literatura do konce 18. století'] },
    { title: 'Epos o Gilgamešovi', author: '---', name: 'Epos o Gilgamešovi', genre: ['Epos'], druh: ['epika'], time: ['Světová a česká literatura do konce 18. století'] },
    { title: 'Utrpení mladého Werthera', author: 'Johann Wolfgang von Goethe', name: 'Utrpení mladého Werthera', genre: ['Dopisníkový román'], druh: ['epika'], time: ['Světová a česká literatura do konce 18. století'] },
    { title: 'Lakomec', author: 'Molière', name: 'Lakomec', genre: ['Komedie'], druh: ['drama'], time: ['Světová a česká literatura do konce 18. století'] },
    { title: 'Misantrop', author: 'Molière', name: 'Misantrop', genre: ['Komedie'], druh: ['drama'], time: ['Světová a česká literatura do konce 18. století'] },
    { title: 'Hamlet', author: 'William Shakespeare', name: 'Hamlet', genre: ['Tragédie'], druh: ['drama'], time: ['Světová a česká literatura do konce 18. století'] },
    { title: 'Othello', author: 'William Shakespeare', name: 'Othello Othelo', genre: ['Tragédie'], druh: ['drama'], time: ['Světová a česká literatura do konce 18. století'] },
    { title: 'Romeo a Julie', author: 'William Shakespeare', name: 'Romeo a Julie', genre: ['Tragédie'], druh: ['drama'], time: ['Světová a česká literatura do konce 18. století'] },
    { title: 'Sonety', author: 'William Shakespeare', name: 'Sonety', genre: ['Sonet'], druh: ['lyrika'], time: ['Světová a česká literatura do konce 18. století'] },
    { title: 'Zkrocení zlé ženy', author: 'William Shakespeare', name: 'Zkrocení zlé ženy', genre: ['Komedie'], druh: ['drama'], time: ['Světová a česká literatura do konce 18. století'] },
    { title: 'Antigona', author: 'Sofokles', name: 'Antigona', genre: ['Tragédie'], druh: ['drama'], time: ['Světová a česká literatura do konce 18. století'] },
    { title: 'Král Oidipus', author: 'Sofokles', name: 'Král Oidipus', genre: ['Tragédie'], druh: ['drama'], time: ['Světová a česká literatura do konce 18. století'] },
    { title: 'Velký testament', author: 'François Villon', name: 'Velký testament Závěť', genre: ['Balada'], druh: ['lyricko-epicke'], time: ['Světová a česká literatura do konce 18. století'] },
    { title: 'Svatý Xaverius', author: 'Jakub Arbes', name: 'Svatý Xaverius', genre: ['Romaneto'], druh: ['epika'], time: ['Světová a česká literatura 19. století'] },
    { title: 'Pýcha a předsudek', author: 'Jane Austenová', name: 'Pýcha a předsudek', genre: ['Sociální román', 'Román'], druh: ['epika'], time: ['Světová a česká literatura 19. století'] },
    { title: 'Květy zla', author: 'Charles Baudelaire', name: 'Květy zla', genre: ['Sbírka básní'], druh: ['lyrika'], time: ['Světová a česká literatura 19. století'] },
    { title: 'Na Větrné hůrce', author: 'Emily Brontëová', name: 'Na Větrné hůrce', genre: ['Gotický román', 'Román'], druh: ['epika'], time: ['Světová a česká literatura 19. století'] },
    { title: 'Chillonský vězeň', author: 'George Gordon Byron', name: 'Chillonský vězeň', genre: ['Básnická povídka'], druh: ['lyricko-epicke'], time: ['Světová a česká literatura 19. století'] },
    { title: 'Idiot', author: 'Fjodor Michajlovič Dostojevskij', name: 'Idiot', genre: ['Psychologický román', 'Román'], druh: ['epika'], time: ['Světová a česká literatura 19. století'] },
    { title: 'Zločin a trest', author: 'Fjodor Michajlovič Dostojevskij', name: 'Zločin a trest', genre: ['Filosofický román', 'Román'], druh: ['epika'], time: ['Světová a česká literatura 19. století'] },
    { title: 'Kytice', author: 'Karel Jaromír Erben', name: 'Kytice', genre: ['Balada'], druh: ['lyricko-epicke'], time: ['Světová a česká literatura 19. století'] },
    { title: 'Paní Bovaryová', author: 'Gustave Flaubert', name: 'Paní Bovaryová', genre: ['Román'], druh: ['epika'], time: ['Světová a česká literatura 19. století'] },
    { title: 'Revizor', author: 'Nikolaj Vasiljevič Gogol', name: 'Revizor', genre: ['Komedie'], druh: ['drama'], time: ['Světová a česká literatura 19. století'] },
    { title: 'Tyrolské elegie', author: 'Karel Havlíček Borovský', name: 'Tyrolské elegie', genre: ['Elegie'], druh: ['lyrika'], time: ['Světová a česká literatura 19. století'] },
    { title: 'Křest sv. Vladimíra', author: 'Karel Havlíček Borovský', name: 'Křest sv. Vladimíra', genre: ['Elegie'], druh: ['lyrika'], time: ['Světová a česká literatura 19. století'] },
    { title: 'Chrám Matky Boží v Paříži', author: 'Victor Hugo', name: 'Chrám Matky Boží v Paříži', genre: ['Gotický román', 'Román'], druh: ['epika'], time: ['Světová a česká literatura 19. století'] },
    { title: 'Bídnici', author: 'Victor Hugo', name: 'Bídnici', genre: ['Sociální román', 'Román'], druh: ['epika'], time: ['Světová a česká literatura 19. století'] },
    { title: 'Staré pověsti české', author: 'Alois Jirásek', name: 'Staré pověsti české', genre: ['Pověst'], druh: ['epika'], time: ['Světová a česká literatura 19. století'] },
    { title: 'Máj', author: 'Karel Hynek Mácha', name: 'Máj', genre: ['Báseň'], druh: ['lyricko-epicke'], time: ['Světová a česká literatura 19. století'] },
    { title: 'Kulička a jiné povídky', author: 'Guy de Maupassant', name: 'Kulička a jiné povídky', genre: ['Povídka'], druh: ['epika'], time: ['Světová a česká literatura 19. století'] },
    { title: 'Maryša', author: 'Vilém a Alois Mrštíkovi', name: 'Maryša', genre: ['Tragédie'], druh: ['drama'], time: ['Světová a česká literatura 19. století'] },
    { title: 'Divá Bára', author: 'Božena Němcová', name: 'Divá Bára', genre: ['Povídka'], druh: ['epika'], time: ['Světová a česká literatura 19. století'] },
    { title: 'Povídky malostranské', author: 'Jan Neruda', name: 'Povídky malostranské', genre: ['Povídka'], druh: ['epika'], time: ['Světová a česká literatura 19. století'] },
    { title: 'Černý kocour a jiné hororové povídky', author: 'Edgar Allan Poe', name: 'Černý kocour a jiné hororové povídky', genre: ['Povídka'], druh: ['epika'], time: ['Světová a česká literatura 19. století'] },
    { title: 'Havran', author: 'Edgar Allan Poe', name: 'Havran', genre: ['Báseň'], druh: ['lyrika'], time: ['Světová a česká literatura 19. století'] },
    { title: 'Evžen Oněgin', author: 'Alexander Sergejevič Puškin', name: 'Evžen Oněgin', genre: ['Román'], druh: ['epika'], time: ['Světová a česká literatura 19. století'] },
    { title: 'Opilý koráb', author: 'Arthur Rimbaud', name: 'Opilý koráb', genre: ['Báseň'], druh: ['lyrika'], time: ['Světová a česká literatura 19. století'] },
    { title: 'Odpoutaný Prométheus', author: 'Percy Bysshe Shelley', name: 'Odpoutaný Prométheus', genre: ['Báseň'], druh: ['lyrika'], time: ['Světová a česká literatura 19. století'] },
    { title: 'Podivný případ doktora Jekylla a pana Hyda', author: 'Robert Louis Stevenson', name: 'Podivný případ doktora Jekylla a pana Hyda', genre: ['Detektivní román', 'Román'], druh: ['epika'], time: ['Světová a česká literatura 19. století'] },
    { title: 'Anna Kareninová', author: 'Lev Nikolajevič Tolstoj', name: 'Anna Kareninová', genre: ['Psychologický román', 'Román'], druh: ['epika'], time: ['Světová a česká literatura 19. století'] },
    { title: 'Strakonický dudák', author: 'Josef Kajetán Tyl', name: 'Strakonický dudák', genre: ['Báchorka drama'], druh: ['drama'], time: ['Světová a česká literatura 19. století'] },
    { title: 'Noc na Karlštejně', author: 'Jaroslav Vrchlický', name: 'Noc na Karlštejně', genre: ['Báseň'], druh: ['lyrika'], time: ['Světová a česká literatura 19. století'] },
    { title: 'Stébla trávy', author: 'Walt Whitman', name: 'Stébla trávy', genre: ['Báseň'], druh: ['lyrika'], time: ['Světová a česká literatura 19. století'] },
    { title: 'Obraz Doriana Graye', author: 'Oscar Wilde', name: 'Obraz Doriana Graye', genre: ['Gotický román', 'Román'], druh: ['epika'], time: ['Světová a česká literatura 19. století'] },
    { title: 'Jak je důležité míti Filipa', author: 'Oscar Wilde', name: 'Jak je důležité míti Filipa', genre: ['Komedie'], druh: ['drama'], time: ['Světová a česká literatura 19. století'] },
    { title: 'Šťastný princ a jiné příběhy', author: 'Oscar Wilde', name: 'Šťastný princ a jiné příběhy', genre: ['Pohádka'], druh: ['epika'], time: ['Světová a česká literatura 19. století'] },
    { title: 'Zabiják', author: 'Émile Zola', name: 'Zabiják', genre: ['Naturalistický román', 'Román'], druh: ['epika'], time: ['Světová a česká literatura 19. století'] },
    { title: 'Stopařův průvodce Galaxií', author: 'Douglas Adams', name: 'Stopařův průvodce Galaxií', genre: ['Vědeckofantastický román', 'Román'], druh: ['epika'], time: ['Světová literatura 20. a 21. století'] },
    { title: 'Alkoholy', author: 'Guillaume Apollinaire', name: 'Alkoholy', genre: ['Básnická sbírka'], druh: ['lyrika'], time: ['Světová literatura 20. a 21. století'] },
    { title: 'Čekání na Godota', author: 'Samuel Beckett', name: 'Čekání na Godota', genre: ['Divadelní hra'], druh: ['drama'], time: ['Světová literatura 20. a 21. století'] },
    { title: '451 stupňů Fahrenheita', author: 'Ray Bradbury', name: '451 stupňů Fahrenheita', genre: ['Dystopický román', 'Román'], druh: ['epika'], time: ['Světová literatura 20. a 21. století'] },
    { title: 'Marťanská kronika', author: 'Ray Bradbury', name: 'Marťanská kronika', genre: ['Sci-fi román', 'Román'], druh: ['epika'], time: ['Světová literatura 20. a 21. století'] },
    { title: 'Hollywood', author: 'Charles Bukowski', name: 'Hollywood', genre: ['Román'], druh: ['epika'], time: ['Světová literatura 20. a 21. století'] },
    { title: 'Mistr a Markétka', author: 'Michail Bulgakov', name: 'Mistr a Markétka', genre: ['Satirický román', 'Román'], druh: ['epika'], time: ['Světová literatura 20. a 21. století'] },
    { title: 'Mechanický pomeranč', author: 'Anthony Burgess', name: 'Mechanický pomeranč', genre: ['Dystopický román', 'Román'], druh: ['epika'], time: ['Světová literatura 20. a 21. století'] },
    { title: 'Cizinec', author: 'Albert Camus', name: 'Cizinec', genre: ['Filozofický román', 'Román'], druh: ['epika'], time: ['Světová literatura 20. a 21. století'] },
    { title: 'Alchymista', author: 'Paulo Coelho', name: 'Alchymista', genre: ['Duchovní román', 'Román'], druh: ['epika'], time: ['Světová literatura 20. a 21. století'] },
    { title: 'Deník Anny Frankové', author: 'Anne Frank', name: 'Deník Anny Frankové', genre: ['Deník'], druh: ['epika'], time: ['Světová literatura 20. a 21. století'] },
    { title: 'Americká tragédie', author: 'Theodore Dreiser', name: 'Americká tragédie', genre: ['Sociální román', 'Román'], druh: ['epika'], time: ['Světová literatura 20. a 21. století'] },
    { title: 'Jméno růže', author: 'Umberto Eco', name: 'Jméno růže', genre: ['Detektivní román', 'Román'], druh: ['epika'], time: ['Světová literatura 20. a 21. století'] },
    { title: 'Malý princ', author: 'Antoine de Saint-Exupéry', name: 'Malý princ', genre: ['Filozofický román', 'Román'], druh: ['epika'], time: ['Světová literatura 20. a 21. století'] },
    { title: 'Velký Gatsby', author: 'F. Scott Fitzgerald', name: 'Velký Gatsby', genre: ['Román'], druh: ['epika'], time: ['Světová literatura 20. a 21. století'] },
    { title: 'Kvílení', author: 'Allen Ginsberg', name: 'Kvílení', genre: ['Básnická sbírka'], druh: ['lyrika'], time: ['Světová literatura 20. a 21. století'] },
    { title: 'Metro 33', author: 'Dmitry Glukhovsky', name: 'Metro 33', genre: ['Postapokalyptický román', 'Román'], druh: ['epika'], time: ['Světová literatura 20. a 21. století'] },
    { title: 'Stařec a moře', author: 'Ernest Hemingway', name: 'Stařec a moře', genre: ['Novela'], druh: ['epika'], time: ['Světová literatura 20. a 21. století'] },
    { title: 'Konec civilizace', author: 'Aldous Huxley', name: 'Konec civilizace', genre: ['Antiutopický román', 'Román'], druh: ['epika'], time: ['Světová literatura 20. a 21. století'] },
    { title: 'My děti ze stanice ZOO', author: 'Christiane F.', name: 'My děti ze stanice ZOO', genre: ['Autobiografický román', 'Román'], druh: ['epika'], time: ['Světová literatura 20. a 21. století'] },
    { title: 'Pán much', author: 'William Golding', name: 'Pán much', genre: ['Alegorický román', 'Román'], druh: ['epika'], time: ['Světová literatura 20. a 21. století'] },
    { title: 'Proces', author: 'Franz Kafka', name: 'Proces', genre: ['Existenciální román', 'Román'], druh: ['epika'], time: ['Světová literatura 20. a 21. století'] },
    { title: 'Proměna a jiné povídky', author: 'Franz Kafka', name: 'Proměna a jiné povídky', genre: ['Krátké povídky'], druh: ['epika'], time: ['Světová literatura 20. a 21. století'] },
    { title: 'Vyhoďme ho z kola ven', author: 'Ken Kesey', name: 'Vyhoďme ho z kola ven', genre: ['Antiutopický román', 'Román'], druh: ['epika'], time: ['Světová literatura 20. a 21. století'] },
    { title: 'Zelená míle', author: 'Stephen King', name: 'Zelená míle', genre: ['Fantasy román', 'Román'], druh: ['epika'], time: ['Světová literatura 20. a 21. století'] },
    { title: 'Řbitov zviřátek', author: 'Stephen King', name: 'Řbitov zviřátek Hřbitov', genre: ['Horrorový román', 'Román'], druh: ['epika'], time: ['Světová literatura 20. a 21. století'] },
    { title: 'Nabarvené ptáče', author: 'Jerzy Kosiński', name: 'Nabarvené ptáče', genre: ['Válečný román', 'Román'], druh: ['epika'], time: ['Světová literatura 20. a 21. století'] },
    { title: 'Sto roků samoty', author: 'Gabriel García Márquez', name: 'Sto roků samoty', genre: ['Román'], druh: ['epika'], time: ['Světová literatura 20. a 21. století'] },
    { title: 'Hra o trůny', author: 'George Raymond Richard Martin', name: 'Hra o trůny', genre: ['Fantasy'], druh: ['epika'], time: ['Světová literatura 20. a 21. století'] },
    { title: 'Betonová zahrada', author: 'Ian McEWan', name: 'Betonová zahrada', genre: ['Rodinný román', 'Román'], druh: ['epika'], time: ['Světová literatura 20. a 21. století'] },
    { title: 'Smrt je mým řemeslem', author: 'Robert Merle', name: 'Smrt je mým řemeslem', genre: ['Román'], druh: ['epika'], time: ['Světová literatura 20. a 21. století'] },
    { title: 'Kafka na pobřeží', author: 'Haruki Murakami', name: 'Kafka na pobřeží', genre: ['Surrealistický román','Román'], druh: ['epika'], time: ['Světová literatura 20. a 21. století'] },
    { title: 'Lolita', author: 'Vladimir Nabokov', name: 'Lolita', genre: ['Psychologický román','Román'], druh: ['epika'], time: ['Světová literatura 20. a 21. století'] },
    { title: '1984', author: 'George Orwell', name: '1984', genre: ['Antiutopistický román','Román'], druh: ['epika'], time: ['Světová literatura 20. a 21. století'] },
    { title: 'Farma zvířat', author: 'George Orwell', name: 'Farma zvířat', genre: ['Antiutopistický román','Román'], druh: ['epika'], time: ['Světová literatura 20. a 21. století'] },
    { title: 'Na západní frontě klid', author: 'Erich Maria Remarque', name: 'Na západní frontě klid', genre: ['Historický román','Román'], druh: ['epika'], time: ['Světová literatura 20. a 21. století'] },
    { title: 'Petr a Lucie', author: 'Romain Rolland', name: 'Petr a Lucie', genre: ['Novela'], druh: ['epika'], time: ['Světová literatura 20. a 21. století'] },
    { title: 'Zaklínač', author: 'Andrzej Sapkowski', name: 'Zaklínač', genre: ['Fantasy'], druh: ['epika'], time: ['Světová literatura 20. a 21. století'] },
    { title: 'Tracyho tygr', author: 'William Saroyan', name: 'Tracyho tygr', genre: ['Novela'], druh: ['epika'], time: ['Světová literatura 20. a 21. století'] },
    { title: 'Pygmalion', author: 'George Bernard Shaw', name: 'Pygmalion', genre: ['Komedie'], druh: ['drama'], time: ['Světová literatura 20. a 21. století'] },
    { title: 'Jeden den Ivana Děnisoviče', author: 'Alexandr Solženicyn', name: 'Jeden den Ivana Děnisoviče', genre: ['Novela'], druh: ['epika'], time: ['Světová literatura 20. a 21. století'] },
    { title: 'O myších a lidech', author: 'John Steinbeck', name: 'O myších a lidech', genre: ['Novela'], druh: ['epika'], time: ['Světová literatura 20. a 21. století'] },
    { title: 'Sophiina volba', author: 'William Clark Styron', name: 'Sophiina volba', genre: ['Psychologický román', 'Román'], druh: ['epika'], time: ['Světová literatura 20. a 21. století'] },
    { title: 'Hobit', author: 'John Ronald Reuel Tolkien', name: 'Hobit', genre: ['Fantasy román', 'Román', 'Fantasy'], druh: ['epika'], time: ['Světová literatura 20. a 21. století'] },
    { title: 'Pán prstenů - Společenstvo prstenu', author: 'John Ronald Reuel Tolkien', name: 'Pán prstenů Společenstvo prstenu', genre: ['Fantasy román', 'Román', 'Fantasy'], druh: ['epika'], time: ['Světová literatura 20. a 21. století'] },
    { title: 'Zlodějka knih', author: 'Markus Zusak', name: 'Zlodějka knih', genre: ['Román'], druh: ['epika'], time: ['Světová literatura 20. a 21. století'] },
    { title: 'Slezské písně', author: 'Petr Bezruč', name: 'Slezské písně', genre: ['Báseň'], druh: ['lyrika'], time: ['Česká literatura 20. a 21. století'] },
    { title: 'Bílá nemoc', author: 'Karel Čapek', name: 'Bílá nemoc', genre: ['Tragédie'], druh: ['drama'], time: ['Česká literatura 20. a 21. století'] },
    { title: 'Matka', author: 'Karel Čapek', name: 'Matka', genre: ['Tragédie'], druh: ['drama'], time: ['Česká literatura 20. a 21. století'] },
    { title: 'Povídky z jedné kapsy', author: 'Karel Čapek', name: 'Povídky z jedné kapsy', genre: ['Povídka'], druh: ['epika'], time: ['Česká literatura 20. a 21. století'] },
    { title: 'RUR', author: 'Karel Čapek', name: 'RUR', genre: ['Tragédie'], druh: ['drama'], time: ['Česká literatura 20. a 21. století'] },
    { title: 'Válka s mloky', author: 'Karel Čapek', name: 'Válka s mloky', genre: ['Romaneto'], druh: ['epika'], time: ['Česká literatura 20. a 21. století'] },
    { title: 'Krysař', author: 'Jaroslav Hašek', name: 'Krysař', genre: ['Povídka'], druh: ['epika'], time: ['Česká literatura 20. a 21. století'] },
    { title: 'Osudy dobrého vojáka Švejka za světové války', author: 'Jaroslav Hašek', name: 'Osudy dobrého vojáka Švejka za světové války', genre: ['Román'], druh: ['epika'], time: ['Česká literatura 20. a 21. století'] },
    { title: 'Audience', author: 'Václav Havel', name: 'Audience', genre: ['Absurdní drama'], druh: ['drama'], time: ['Česká literatura 20. a 21. století'] },
    { title: 'Žebrácká opera', author: 'Václav Havel', name: 'Žebrácká opera', genre: ['Komedie'], druh: ['drama'], time: ['Česká literatura 20. a 21. století'] },
    { title: 'Petrolejové lampy', author: 'Jan Neruda', name: 'Petrolejové lampy', genre: ['Elegie'], druh: ['lyrika'], time: ['Česká literatura 20. a 21. století'] },
    { title: 'Obsluhoval jsem anglického krále', author: 'Bohumil Hrabal', name: 'Obsluhoval jsem anglického krále', genre: ['Historický román', 'Román'], druh: ['epika'], time: ['Česká literatura 20. a 21. století'] },
    { title: 'Ostře sledované vlaky', author: 'Bohumil Hrabal', name: 'Ostře sledované vlaky', genre: ['Novela'], druh: ['epika'], time: ['Česká literatura 20. a 21. století'] },
    { title: 'Příliš hlučná samota', author: 'Bohumil Hrabal', name: 'Příliš hlučná samota', genre: ['Sociální román', 'Román'], druh: ['epika'], time: ['Česká literatura 20. a 21. století'] },
    { title: 'Blues pro bláznivou holku', author: 'Milan Kundera', name: 'Blues pro bláznivou holku', genre: ['Filozofický román', 'Román'], druh: ['epika'], time: ['Česká literatura 20. a 21. století'] },
    { title: 'Spalovač mrtvol', author: 'Josef Škvorecký', name: 'Spalovač mrtvol', genre: ['Historický román', 'Román'], druh: ['epika'], time: ['Česká literatura 20. a 21. století'] },
    { title: 'Saturnin', author: 'Zdeněk Jirotka', name: 'Saturnin', genre: ['Humoristický román', 'Román'], druh: ['epika'], time: ['Česká literatura 20. a 21. století'] },
    { title: 'Memento', author: 'Eduard Bass', name: 'Memento', genre: ['Báseň'], druh: ['lyrika'], time: ['Česká literatura 20. a 21. století'] },
    { title: 'Směšné lásky', author: 'Milan Kundera', name: 'Směšné lásky', genre: ['Filozofický román', 'Román'], druh: ['epika'], time: ['Česká literatura 20. a 21. století'] },
    { title: 'Žert', author: 'Milan Kundera', name: 'Žert', genre: ['Existenciální román', 'Román'], druh: ['epika'], time: ['Česká literatura 20. a 21. století'] },
    { title: 'Jozova Hanule', author: 'Marie Majerová', name: 'Jozova Hanule', genre: ['Historický román', 'Román'], druh: ['epika'], time: ['Česká literatura 20. a 21. století'] },
    { title: 'Modlitba pro Kateřinu Horovitzovou', author: 'Arnošt Lustig', name: 'Modlitba pro Kateřinu Horovitzovou', genre: ['Novela'], druh: ['epika'], time: ['Česká literatura 20. a 21. století'] },
    { title: 'Hana', author: 'Alena Mornštajnová', name: 'Hana', genre: ['Rodinný román', 'Román'], druh: ['epika'], time: ['Česká literatura 20. a 21. století'] },
    { title: 'Tiché roky', author: 'Alena Mornštajnová', name: 'Tiché roky', genre: ['Historický román', 'Román'], druh: ['epika'], time: ['Česká literatura 20. a 21. století'] },
    { title: 'Edison', author: 'Vítězslav Nezval', name: 'Edison', genre: ['Báseň'], druh: ['lyrika'], time: ['Česká literatura 20. a 21. století'] },
    { title: 'Manon Lescaut', author: 'Vítězslav Nezval', name: 'Manon Lescaut', genre: ['Báseň'], druh: ['lyrika'], time: ['Česká literatura 20. a 21. století'] },
    { title: 'Valerie a týden divů', author: 'Vítězslav Nezval', name: 'Valerie a týden divů', genre: ['Báseň'], druh: ['lyrika'], time: ['Česká literatura 20. a 21. století'] },
    { title: 'Nikola Šuhajloupežník', author: 'Karel Michal', name: 'Nikola Šuhajloupežník', genre: ['Balada'], druh: ['Lyricko-epické'], time: ['Česká literatura 20. a 21. století'] },
    { title: 'Romeo, Julie a tma', author: 'Jiří Otčenášek', name: 'Romeo, Julie a tma', genre: ['Báseň'], druh: ['lyrika'], time: ['Česká literatura 20. a 21. století'] },
    { title: 'Smrt krásných srnců', author: 'Karel Pavel', name: 'Smrt krásných srnců', genre: ['Romaneto'], druh: ['epika'], time: ['Česká literatura 20. a 21. století'] },
    { title: 'Bylo nás pět', author: 'Jaroslav Poláček', name: 'Bylo nás pět', genre: ['Romaneto'], druh: ['epika'], time: ['Česká literatura 20. a 21. století'] },
    { title: 'Na vlnách T. S. F.', author: 'Jaroslav Seifert', name: 'Na vlnách T. S. F.', genre: ['Báseň'], druh: ['lyrika'], time: ['Česká literatura 20. a 21. století'] },
    { title: 'Lvíče', author: 'Josef Škvorecký', name: 'Lvíče', genre: ['Romaneto'], druh: ['epika'], time: ['Česká literatura 20. a 21. století'] },
    { title: 'Markéta Lazarová', author: 'Vladislav Vančura', name: 'Markéta Lazarová', genre: ['Historický román', 'Román'], druh: ['epika'], time: ['Česká literatura 20. a 21. století'] },
    { title: 'Rozmarné léto', author: 'Vladislav Vančura', name: 'Rozmarné léto', genre: ['Romantický román', 'Román'], druh: ['epika'], time: ['Česká literatura 20. a 21. století'] },
    { title: 'Báječná léta pod psa', author: 'Michal Viewegh', name: 'Báječná léta pod psa', genre: ['Romaneto'], druh: ['epika'], time: ['Česká literatura 20. a 21. století'] },
    { title: 'Těžká hodina', author: 'Jiří Wolker', name: 'Těžká hodina', genre: ['Báseň'], druh: ['lyrika'], time: ['Česká literatura 20. a 21. století'] }
];

const inputBooks = [
    { title: 'Bible: NZ (Evangelium podle Jana)', author: '---', name: 'Bible: NZ (Evangelium podle Jana)', genre: ['Svatá kniha'], druh: ['epika'], time: ['Světová a česká literatura do konce 18. století'] },
    { title: 'Bible: SZ (první nebo druhá kniha Mojžíšova)', author: '---', name: 'Bible: SZ (první nebo druhá kniha Mojžíšova)', genre: ['Svatá kniha'], druh: ['epika'], time: ['Světová a česká literatura do konce 18. století'] },
    { title: 'Dekameron', author: 'Giovanni Boccaccio', name: 'Dekameron', genre: ['Novela'], druh: ['epika'], time: ['Světová a česká literatura do konce 18. století'] },
    { title: 'Důmyslný rytíř Don Quijote de la Mancha', author: 'Miguel de Cervantes y Saavedra', name: 'Důmyslný rytíř Don Quijote de la Mancha', genre: ['Pikareskní román'], druh: ['epika'], time: ['Světová a česká literatura do konce 18. století'] },
    { title: 'Jeptiška', author: 'Denis Diderot', name: 'Jeptiška', genre: ['Filosofický román', 'Román'], druh: ['epika'], time: ['Světová a česká literatura do konce 18. století'] },
    { title: 'Epos o Gilgamešovi', author: '---', name: 'Epos o Gilgamešovi', genre: ['Epos'], druh: ['epika'], time: ['Světová a česká literatura do konce 18. století'] },
    { title: 'Utrpení mladého Werthera', author: 'Johann Wolfgang von Goethe', name: 'Utrpení mladého Werthera', genre: ['Dopisníkový román'], druh: ['epika'], time: ['Světová a česká literatura do konce 18. století'] },
    { title: 'Lakomec', author: 'Molière', name: 'Lakomec', genre: ['Komedie'], druh: ['drama'], time: ['Světová a česká literatura do konce 18. století'] },
    { title: 'Misantrop', author: 'Molière', name: 'Misantrop', genre: ['Komedie'], druh: ['drama'], time: ['Světová a česká literatura do konce 18. století'] },
    { title: 'Hamlet', author: 'William Shakespeare', name: 'Hamlet', genre: ['Tragédie'], druh: ['drama'], time: ['Světová a česká literatura do konce 18. století'] },
    { title: 'Othello', author: 'William Shakespeare', name: 'Othello Othelo', genre: ['Tragédie'], druh: ['drama'], time: ['Světová a česká literatura do konce 18. století'] },
    { title: 'Romeo a Julie', author: 'William Shakespeare', name: 'Romeo a Julie', genre: ['Tragédie'], druh: ['drama'], time: ['Světová a česká literatura do konce 18. století'] },
    { title: 'Sonety', author: 'William Shakespeare', name: 'Sonety', genre: ['Sonet'], druh: ['lyrika'], time: ['Světová a česká literatura do konce 18. století'] },
    { title: 'Zkrocení zlé ženy', author: 'William Shakespeare', name: 'Zkrocení zlé ženy', genre: ['Komedie'], druh: ['drama'], time: ['Světová a česká literatura do konce 18. století'] },
    { title: 'Antigona', author: 'Sofokles', name: 'Antigona', genre: ['Tragédie'], druh: ['drama'], time: ['Světová a česká literatura do konce 18. století'] },
    { title: 'Král Oidipus', author: 'Sofokles', name: 'Král Oidipus', genre: ['Tragédie'], druh: ['drama'], time: ['Světová a česká literatura do konce 18. století'] },
    { title: 'Velký testament', author: 'François Villon', name: 'Velký testament Závěť', genre: ['Balada'], druh: ['lyricko-epicke'], time: ['Světová a česká literatura do konce 18. století'] },
    { title: 'Svatý Xaverius', author: 'Jakub Arbes', name: 'Svatý Xaverius', genre: ['Romaneto'], druh: ['epika'], time: ['Světová a česká literatura 19. století'] },
    { title: 'Pýcha a předsudek', author: 'Jane Austenová', name: 'Pýcha a předsudek', genre: ['Sociální román', 'Román'], druh: ['epika'], time: ['Světová a česká literatura 19. století'] },
    { title: 'Květy zla', author: 'Charles Baudelaire', name: 'Květy zla', genre: ['Sbírka básní'], druh: ['lyrika'], time: ['Světová a česká literatura 19. století'] },
    { title: 'Na Větrné hůrce', author: 'Emily Brontëová', name: 'Na Větrné hůrce', genre: ['Gotický román', 'Román'], druh: ['epika'], time: ['Světová a česká literatura 19. století'] },
    { title: 'Chillonský vězeň', author: 'George Gordon Byron', name: 'Chillonský vězeň', genre: ['Básnická povídka'], druh: ['lyricko-epicke'], time: ['Světová a česká literatura 19. století'] },
    { title: 'Idiot', author: 'Fjodor Michajlovič Dostojevskij', name: 'Idiot', genre: ['Psychologický román', 'Román'], druh: ['epika'], time: ['Světová a česká literatura 19. století'] },
    { title: 'Zločin a trest', author: 'Fjodor Michajlovič Dostojevskij', name: 'Zločin a trest', genre: ['Filosofický román', 'Román'], druh: ['epika'], time: ['Světová a česká literatura 19. století'] },
    { title: 'Kytice', author: 'Karel Jaromír Erben', name: 'Kytice', genre: ['Balada'], druh: ['lyricko-epicke'], time: ['Světová a česká literatura 19. století'] },
    { title: 'Paní Bovaryová', author: 'Gustave Flaubert', name: 'Paní Bovaryová', genre: ['Román'], druh: ['epika'], time: ['Světová a česká literatura 19. století'] },
    { title: 'Revizor', author: 'Nikolaj Vasiljevič Gogol', name: 'Revizor', genre: ['Komedie'], druh: ['drama'], time: ['Světová a česká literatura 19. století'] },
    { title: 'Tyrolské elegie', author: 'Karel Havlíček Borovský', name: 'Tyrolské elegie', genre: ['Elegie'], druh: ['lyrika'], time: ['Světová a česká literatura 19. století'] },
    { title: 'Křest sv. Vladimíra', author: 'Karel Havlíček Borovský', name: 'Křest sv. Vladimíra', genre: ['Elegie'], druh: ['lyrika'], time: ['Světová a česká literatura 19. století'] },
    { title: 'Chrám Matky Boží v Paříži', author: 'Victor Hugo', name: 'Chrám Matky Boží v Paříži', genre: ['Gotický román', 'Román'], druh: ['epika'], time: ['Světová a česká literatura 19. století'] },
    { title: 'Bídnici', author: 'Victor Hugo', name: 'Bídnici', genre: ['Sociální román', 'Román'], druh: ['epika'], time: ['Světová a česká literatura 19. století'] },
    { title: 'Staré pověsti české', author: 'Alois Jirásek', name: 'Staré pověsti české', genre: ['Pověst'], druh: ['epika'], time: ['Světová a česká literatura 19. století'] },
    { title: 'Máj', author: 'Karel Hynek Mácha', name: 'Máj', genre: ['Báseň'], druh: ['lyricko-epicke'], time: ['Světová a česká literatura 19. století'] },
    { title: 'Kulička a jiné povídky', author: 'Guy de Maupassant', name: 'Kulička a jiné povídky', genre: ['Povídka'], druh: ['epika'], time: ['Světová a česká literatura 19. století'] },
    { title: 'Maryša', author: 'Vilém a Alois Mrštíkovi', name: 'Maryša', genre: ['Tragédie'], druh: ['drama'], time: ['Světová a česká literatura 19. století'] },
    { title: 'Divá Bára', author: 'Božena Němcová', name: 'Divá Bára', genre: ['Povídka'], druh: ['epika'], time: ['Světová a česká literatura 19. století'] },
    { title: 'Povídky malostranské', author: 'Jan Neruda', name: 'Povídky malostranské', genre: ['Povídka'], druh: ['epika'], time: ['Světová a česká literatura 19. století'] },
    { title: 'Černý kocour a jiné hororové povídky', author: 'Edgar Allan Poe', name: 'Černý kocour a jiné hororové povídky', genre: ['Povídka'], druh: ['epika'], time: ['Světová a česká literatura 19. století'] },
    { title: 'Havran', author: 'Edgar Allan Poe', name: 'Havran', genre: ['Báseň'], druh: ['lyrika'], time: ['Světová a česká literatura 19. století'] },
    { title: 'Evžen Oněgin', author: 'Alexander Sergejevič Puškin', name: 'Evžen Oněgin', genre: ['Román'], druh: ['epika'], time: ['Světová a česká literatura 19. století'] },
    { title: 'Opilý koráb', author: 'Arthur Rimbaud', name: 'Opilý koráb', genre: ['Báseň'], druh: ['lyrika'], time: ['Světová a česká literatura 19. století'] },
    { title: 'Odpoutaný Prométheus', author: 'Percy Bysshe Shelley', name: 'Odpoutaný Prométheus', genre: ['Báseň'], druh: ['lyrika'], time: ['Světová a česká literatura 19. století'] },
    { title: 'Podivný případ doktora Jekylla a pana Hyda', author: 'Robert Louis Stevenson', name: 'Podivný případ doktora Jekylla a pana Hyda', genre: ['Detektivní román', 'Román'], druh: ['epika'], time: ['Světová a česká literatura 19. století'] },
    { title: 'Anna Kareninová', author: 'Lev Nikolajevič Tolstoj', name: 'Anna Kareninová', genre: ['Psychologický román', 'Román'], druh: ['epika'], time: ['Světová a česká literatura 19. století'] },
    { title: 'Strakonický dudák', author: 'Josef Kajetán Tyl', name: 'Strakonický dudák', genre: ['Báchorka drama'], druh: ['drama'], time: ['Světová a česká literatura 19. století'] },
    { title: 'Noc na Karlštejně', author: 'Jaroslav Vrchlický', name: 'Noc na Karlštejně', genre: ['Báseň'], druh: ['lyrika'], time: ['Světová a česká literatura 19. století'] },
    { title: 'Stébla trávy', author: 'Walt Whitman', name: 'Stébla trávy', genre: ['Báseň'], druh: ['lyrika'], time: ['Světová a česká literatura 19. století'] },
    { title: 'Obraz Doriana Graye', author: 'Oscar Wilde', name: 'Obraz Doriana Graye', genre: ['Gotický román', 'Román'], druh: ['epika'], time: ['Světová a česká literatura 19. století'] },
    { title: 'Jak je důležité míti Filipa', author: 'Oscar Wilde', name: 'Jak je důležité míti Filipa', genre: ['Komedie'], druh: ['drama'], time: ['Světová a česká literatura 19. století'] },
    { title: 'Šťastný princ a jiné příběhy', author: 'Oscar Wilde', name: 'Šťastný princ a jiné příběhy', genre: ['Pohádka'], druh: ['epika'], time: ['Světová a česká literatura 19. století'] },
    { title: 'Zabiják', author: 'Émile Zola', name: 'Zabiják', genre: ['Naturalistický román', 'Román'], druh: ['epika'], time: ['Světová a česká literatura 19. století'] },
    { title: 'Stopařův průvodce Galaxií', author: 'Douglas Adams', name: 'Stopařův průvodce Galaxií', genre: ['Vědeckofantastický román', 'Román'], druh: ['epika'], time: ['Světová literatura 20. a 21. století'] },
    { title: 'Alkoholy', author: 'Guillaume Apollinaire', name: 'Alkoholy', genre: ['Básnická sbírka'], druh: ['lyrika'], time: ['Světová literatura 20. a 21. století'] },
    { title: 'Čekání na Godota', author: 'Samuel Beckett', name: 'Čekání na Godota', genre: ['Divadelní hra'], druh: ['drama'], time: ['Světová literatura 20. a 21. století'] },
    { title: '451 stupňů Fahrenheita', author: 'Ray Bradbury', name: '451 stupňů Fahrenheita', genre: ['Dystopický román', 'Román'], druh: ['epika'], time: ['Světová literatura 20. a 21. století'] },
    { title: 'Marťanská kronika', author: 'Ray Bradbury', name: 'Marťanská kronika', genre: ['Sci-fi román', 'Román'], druh: ['epika'], time: ['Světová literatura 20. a 21. století'] },
    { title: 'Hollywood', author: 'Charles Bukowski', name: 'Hollywood', genre: ['Román'], druh: ['epika'], time: ['Světová literatura 20. a 21. století'] },
    { title: 'Mistr a Markétka', author: 'Michail Bulgakov', name: 'Mistr a Markétka', genre: ['Satirický román', 'Román'], druh: ['epika'], time: ['Světová literatura 20. a 21. století'] },
    { title: 'Mechanický pomeranč', author: 'Anthony Burgess', name: 'Mechanický pomeranč', genre: ['Dystopický román', 'Román'], druh: ['epika'], time: ['Světová literatura 20. a 21. století'] },
    { title: 'Cizinec', author: 'Albert Camus', name: 'Cizinec', genre: ['Filozofický román', 'Román'], druh: ['epika'], time: ['Světová literatura 20. a 21. století'] },
    { title: 'Alchymista', author: 'Paulo Coelho', name: 'Alchymista', genre: ['Duchovní román', 'Román'], druh: ['epika'], time: ['Světová literatura 20. a 21. století'] },
    { title: 'Deník Anny Frankové', author: 'Anne Frank', name: 'Deník Anny Frankové', genre: ['Deník'], druh: ['epika'], time: ['Světová literatura 20. a 21. století'] },
    { title: 'Americká tragédie', author: 'Theodore Dreiser', name: 'Americká tragédie', genre: ['Sociální román', 'Román'], druh: ['epika'], time: ['Světová literatura 20. a 21. století'] },
    { title: 'Jméno růže', author: 'Umberto Eco', name: 'Jméno růže', genre: ['Detektivní román', 'Román'], druh: ['epika'], time: ['Světová literatura 20. a 21. století'] },
    { title: 'Malý princ', author: 'Antoine de Saint-Exupéry', name: 'Malý princ', genre: ['Filozofický román', 'Román'], druh: ['epika'], time: ['Světová literatura 20. a 21. století'] },
    { title: 'Velký Gatsby', author: 'F. Scott Fitzgerald', name: 'Velký Gatsby', genre: ['Román'], druh: ['epika'], time: ['Světová literatura 20. a 21. století'] },
    { title: 'Kvílení', author: 'Allen Ginsberg', name: 'Kvílení', genre: ['Básnická sbírka'], druh: ['lyrika'], time: ['Světová literatura 20. a 21. století'] },
    { title: 'Metro 33', author: 'Dmitry Glukhovsky', name: 'Metro 33', genre: ['Postapokalyptický román', 'Román'], druh: ['epika'], time: ['Světová literatura 20. a 21. století'] },
    { title: 'Stařec a moře', author: 'Ernest Hemingway', name: 'Stařec a moře', genre: ['Novela'], druh: ['epika'], time: ['Světová literatura 20. a 21. století'] },
    { title: 'Konec civilizace', author: 'Aldous Huxley', name: 'Konec civilizace', genre: ['Antiutopický román', 'Román'], druh: ['epika'], time: ['Světová literatura 20. a 21. století'] },
    { title: 'My děti ze stanice ZOO', author: 'Christiane F.', name: 'My děti ze stanice ZOO', genre: ['Autobiografický román', 'Román'], druh: ['epika'], time: ['Světová literatura 20. a 21. století'] },
    { title: 'Pán much', author: 'William Golding', name: 'Pán much', genre: ['Alegorický román', 'Román'], druh: ['epika'], time: ['Světová literatura 20. a 21. století'] },
    { title: 'Proces', author: 'Franz Kafka', name: 'Proces', genre: ['Existenciální román', 'Román'], druh: ['epika'], time: ['Světová literatura 20. a 21. století'] },
    { title: 'Proměna a jiné povídky', author: 'Franz Kafka', name: 'Proměna a jiné povídky', genre: ['Krátké povídky'], druh: ['epika'], time: ['Světová literatura 20. a 21. století'] },
    { title: 'Vyhoďme ho z kola ven', author: 'Ken Kesey', name: 'Vyhoďme ho z kola ven', genre: ['Antiutopický román', 'Román'], druh: ['epika'], time: ['Světová literatura 20. a 21. století'] },
    { title: 'Zelená míle', author: 'Stephen King', name: 'Zelená míle', genre: ['Fantasy román', 'Román'], druh: ['epika'], time: ['Světová literatura 20. a 21. století'] },
    { title: 'Řbitov zviřátek', author: 'Stephen King', name: 'Řbitov zviřátek Hřbitov', genre: ['Horrorový román', 'Román'], druh: ['epika'], time: ['Světová literatura 20. a 21. století'] },
    { title: 'Nabarvené ptáče', author: 'Jerzy Kosiński', name: 'Nabarvené ptáče', genre: ['Válečný román', 'Román'], druh: ['epika'], time: ['Světová literatura 20. a 21. století'] },
    { title: 'Sto roků samoty', author: 'Gabriel García Márquez', name: 'Sto roků samoty', genre: ['Román'], druh: ['epika'], time: ['Světová literatura 20. a 21. století'] },
    { title: 'Hra o trůny', author: 'George Raymond Richard Martin', name: 'Hra o trůny', genre: ['Fantasy'], druh: ['epika'], time: ['Světová literatura 20. a 21. století'] },
    { title: 'Betonová zahrada', author: 'Ian McEWan', name: 'Betonová zahrada', genre: ['Rodinný román', 'Román'], druh: ['epika'], time: ['Světová literatura 20. a 21. století'] },
    { title: 'Smrt je mým řemeslem', author: 'Robert Merle', name: 'Smrt je mým řemeslem', genre: ['Román'], druh: ['epika'], time: ['Světová literatura 20. a 21. století'] },
    { title: 'Kafka na pobřeží', author: 'Haruki Murakami', name: 'Kafka na pobřeží', genre: ['Surrealistický román','Román'], druh: ['epika'], time: ['Světová literatura 20. a 21. století'] },
    { title: 'Lolita', author: 'Vladimir Nabokov', name: 'Lolita', genre: ['Psychologický román','Román'], druh: ['epika'], time: ['Světová literatura 20. a 21. století'] },
    { title: '1984', author: 'George Orwell', name: '1984', genre: ['Antiutopistický román','Román'], druh: ['epika'], time: ['Světová literatura 20. a 21. století'] },
    { title: 'Farma zvířat', author: 'George Orwell', name: 'Farma zvířat', genre: ['Antiutopistický román','Román'], druh: ['epika'], time: ['Světová literatura 20. a 21. století'] },
    { title: 'Na západní frontě klid', author: 'Erich Maria Remarque', name: 'Na západní frontě klid', genre: ['Historický román','Román'], druh: ['epika'], time: ['Světová literatura 20. a 21. století'] },
    { title: 'Petr a Lucie', author: 'Romain Rolland', name: 'Petr a Lucie', genre: ['Novela'], druh: ['epika'], time: ['Světová literatura 20. a 21. století'] },
    { title: 'Zaklínač', author: 'Andrzej Sapkowski', name: 'Zaklínač', genre: ['Fantasy'], druh: ['epika'], time: ['Světová literatura 20. a 21. století'] },
    { title: 'Tracyho tygr', author: 'William Saroyan', name: 'Tracyho tygr', genre: ['Novela'], druh: ['epika'], time: ['Světová literatura 20. a 21. století'] },
    { title: 'Pygmalion', author: 'George Bernard Shaw', name: 'Pygmalion', genre: ['Komedie'], druh: ['drama'], time: ['Světová literatura 20. a 21. století'] },
    { title: 'Jeden den Ivana Děnisoviče', author: 'Alexandr Solženicyn', name: 'Jeden den Ivana Děnisoviče', genre: ['Novela'], druh: ['epika'], time: ['Světová literatura 20. a 21. století'] },
    { title: 'O myších a lidech', author: 'John Steinbeck', name: 'O myších a lidech', genre: ['Novela'], druh: ['epika'], time: ['Světová literatura 20. a 21. století'] },
    { title: 'Sophiina volba', author: 'William Clark Styron', name: 'Sophiina volba', genre: ['Psychologický román', 'Román'], druh: ['epika'], time: ['Světová literatura 20. a 21. století'] },
    { title: 'Hobit', author: 'John Ronald Reuel Tolkien', name: 'Hobit', genre: ['Fantasy román', 'Román', 'Fantasy'], druh: ['epika'], time: ['Světová literatura 20. a 21. století'] },
    { title: 'Pán prstenů - Společenstvo prstenu', author: 'John Ronald Reuel Tolkien', name: 'Pán prstenů Společenstvo prstenu', genre: ['Fantasy román', 'Román', 'Fantasy'], druh: ['epika'], time: ['Světová literatura 20. a 21. století'] },
    { title: 'Zlodějka knih', author: 'Markus Zusak', name: 'Zlodějka knih', genre: ['Román'], druh: ['epika'], time: ['Světová literatura 20. a 21. století'] },
    { title: 'Slezské písně', author: 'Petr Bezruč', name: 'Slezské písně', genre: ['Báseň'], druh: ['lyrika'], time: ['Česká literatura 20. a 21. století'] },
    { title: 'Bílá nemoc', author: 'Karel Čapek', name: 'Bílá nemoc', genre: ['Tragédie'], druh: ['drama'], time: ['Česká literatura 20. a 21. století'] },
    { title: 'Matka', author: 'Karel Čapek', name: 'Matka', genre: ['Tragédie'], druh: ['drama'], time: ['Česká literatura 20. a 21. století'] },
    { title: 'Povídky z jedné kapsy', author: 'Karel Čapek', name: 'Povídky z jedné kapsy', genre: ['Povídka'], druh: ['epika'], time: ['Česká literatura 20. a 21. století'] },
    { title: 'RUR', author: 'Karel Čapek', name: 'RUR', genre: ['Tragédie'], druh: ['drama'], time: ['Česká literatura 20. a 21. století'] },
    { title: 'Válka s mloky', author: 'Karel Čapek', name: 'Válka s mloky', genre: ['Romaneto'], druh: ['epika'], time: ['Česká literatura 20. a 21. století'] },
    { title: 'Krysař', author: 'Jaroslav Hašek', name: 'Krysař', genre: ['Povídka'], druh: ['epika'], time: ['Česká literatura 20. a 21. století'] },
    { title: 'Osudy dobrého vojáka Švejka za světové války', author: 'Jaroslav Hašek', name: 'Osudy dobrého vojáka Švejka za světové války', genre: ['Román'], druh: ['epika'], time: ['Česká literatura 20. a 21. století'] },
    { title: 'Audience', author: 'Václav Havel', name: 'Audience', genre: ['Absurdní drama'], druh: ['drama'], time: ['Česká literatura 20. a 21. století'] },
    { title: 'Žebrácká opera', author: 'Václav Havel', name: 'Žebrácká opera', genre: ['Komedie'], druh: ['drama'], time: ['Česká literatura 20. a 21. století'] },
    { title: 'Petrolejové lampy', author: 'Jan Neruda', name: 'Petrolejové lampy', genre: ['Elegie'], druh: ['lyrika'], time: ['Česká literatura 20. a 21. století'] },
    { title: 'Obsluhoval jsem anglického krále', author: 'Bohumil Hrabal', name: 'Obsluhoval jsem anglického krále', genre: ['Historický román', 'Román'], druh: ['epika'], time: ['Česká literatura 20. a 21. století'] },
    { title: 'Ostře sledované vlaky', author: 'Bohumil Hrabal', name: 'Ostře sledované vlaky', genre: ['Novela'], druh: ['epika'], time: ['Česká literatura 20. a 21. století'] },
    { title: 'Příliš hlučná samota', author: 'Bohumil Hrabal', name: 'Příliš hlučná samota', genre: ['Sociální román', 'Román'], druh: ['epika'], time: ['Česká literatura 20. a 21. století'] },
    { title: 'Blues pro bláznivou holku', author: 'Milan Kundera', name: 'Blues pro bláznivou holku', genre: ['Filozofický román', 'Román'], druh: ['epika'], time: ['Česká literatura 20. a 21. století'] },
    { title: 'Spalovač mrtvol', author: 'Josef Škvorecký', name: 'Spalovač mrtvol', genre: ['Historický román', 'Román'], druh: ['epika'], time: ['Česká literatura 20. a 21. století'] },
    { title: 'Saturnin', author: 'Zdeněk Jirotka', name: 'Saturnin', genre: ['Humoristický román', 'Román'], druh: ['epika'], time: ['Česká literatura 20. a 21. století'] },
    { title: 'Memento', author: 'Eduard Bass', name: 'Memento', genre: ['Báseň'], druh: ['lyrika'], time: ['Česká literatura 20. a 21. století'] },
    { title: 'Směšné lásky', author: 'Milan Kundera', name: 'Směšné lásky', genre: ['Filozofický román', 'Román'], druh: ['epika'], time: ['Česká literatura 20. a 21. století'] },
    { title: 'Žert', author: 'Milan Kundera', name: 'Žert', genre: ['Existenciální román', 'Román'], druh: ['epika'], time: ['Česká literatura 20. a 21. století'] },
    { title: 'Jozova Hanule', author: 'Marie Majerová', name: 'Jozova Hanule', genre: ['Historický román', 'Román'], druh: ['epika'], time: ['Česká literatura 20. a 21. století'] },
    { title: 'Modlitba pro Kateřinu Horovitzovou', author: 'Arnošt Lustig', name: 'Modlitba pro Kateřinu Horovitzovou', genre: ['Novela'], druh: ['epika'], time: ['Česká literatura 20. a 21. století'] },
    { title: 'Hana', author: 'Alena Mornštajnová', name: 'Hana', genre: ['Rodinný román', 'Román'], druh: ['epika'], time: ['Česká literatura 20. a 21. století'] },
    { title: 'Tiché roky', author: 'Alena Mornštajnová', name: 'Tiché roky', genre: ['Historický román', 'Román'], druh: ['epika'], time: ['Česká literatura 20. a 21. století'] },
    { title: 'Edison', author: 'Vítězslav Nezval', name: 'Edison', genre: ['Báseň'], druh: ['lyrika'], time: ['Česká literatura 20. a 21. století'] },
    { title: 'Manon Lescaut', author: 'Vítězslav Nezval', name: 'Manon Lescaut', genre: ['Báseň'], druh: ['lyrika'], time: ['Česká literatura 20. a 21. století'] },
    { title: 'Valerie a týden divů', author: 'Vítězslav Nezval', name: 'Valerie a týden divů', genre: ['Báseň'], druh: ['lyrika'], time: ['Česká literatura 20. a 21. století'] },
    { title: 'Nikola Šuhajloupežník', author: 'Karel Michal', name: 'Nikola Šuhajloupežník', genre: ['Balada'], druh: ['Lyricko-epické'], time: ['Česká literatura 20. a 21. století'] },
    { title: 'Romeo, Julie a tma', author: 'Jiří Otčenášek', name: 'Romeo, Julie a tma', genre: ['Báseň'], druh: ['lyrika'], time: ['Česká literatura 20. a 21. století'] },
    { title: 'Smrt krásných srnců', author: 'Karel Pavel', name: 'Smrt krásných srnců', genre: ['Romaneto'], druh: ['epika'], time: ['Česká literatura 20. a 21. století'] },
    { title: 'Bylo nás pět', author: 'Jaroslav Poláček', name: 'Bylo nás pět', genre: ['Romaneto'], druh: ['epika'], time: ['Česká literatura 20. a 21. století'] },
    { title: 'Na vlnách T. S. F.', author: 'Jaroslav Seifert', name: 'Na vlnách T. S. F.', genre: ['Báseň'], druh: ['lyrika'], time: ['Česká literatura 20. a 21. století'] },
    { title: 'Lvíče', author: 'Josef Škvorecký', name: 'Lvíče', genre: ['Romaneto'], druh: ['epika'], time: ['Česká literatura 20. a 21. století'] },
    { title: 'Markéta Lazarová', author: 'Vladislav Vančura', name: 'Markéta Lazarová', genre: ['Historický román', 'Román'], druh: ['epika'], time: ['Česká literatura 20. a 21. století'] },
    { title: 'Rozmarné léto', author: 'Vladislav Vančura', name: 'Rozmarné léto', genre: ['Romantický román', 'Román'], druh: ['epika'], time: ['Česká literatura 20. a 21. století'] },
    { title: 'Báječná léta pod psa', author: 'Michal Viewegh', name: 'Báječná léta pod psa', genre: ['Romaneto'], druh: ['epika'], time: ['Česká literatura 20. a 21. století'] },
    { title: 'Těžká hodina', author: 'Jiří Wolker', name: 'Těžká hodina', genre: ['Báseň'], druh: ['lyrika'], time: ['Česká literatura 20. a 21. století'] }
];